#python files to ask for foodstuff bought from the market
print("what did you buy?")
yam=input()
print("enter yam amount")
amountyam=float(input())
print("what else did you buy?")
cassava=input()
print("enter cassava ammount")
amountcassava=float(input())
print("Did you buy any other thing?")
groundnutoil=input()
print("enter groundnut oil amount")
amountgoil=float(input())
print("Any other thing?")
meat=input()
print("enter meat amount")
amountmeat=float(input())
print("Is that all?")
maize=input()
print("enter maize amount")
amountmaize=float(input())
total=amountyam + amountcassava + amountgoil + amountmeat + amountmaize
print("My purchase details are : "  + yam + "," + str(amountyam) + "," + cassava + "," + str(amountcassava)+ "," + groundnutoil + "," + str(amountgoil)+ "," + meat + "," +str(amountmeat)+ "," + maize + "," +str(amountmaize)+ "," + "The total: " + str(total))